# -*- coding: utf-8 -*-
"""droneforensicsEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIcLIAKsOfYZDbNBuSJRL_6ko5F5tAhe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = "telemetry_logs(DF005).csv"
df = pd.read_csv(file_path)


print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")

print("\nBasic Info:")
print(df.info())

print("\nSummary Statistics (Numeric Columns):")
print(df.describe().T.head(10))


missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
missing_pct = (missing / len(df)) * 100


missing_df = pd.DataFrame({
    'Missing Values': missing,
    '% Missing': missing_pct
})
print("\n Top Missing Columns:")
print(missing_df.head(15))

# Plot missingness
plt.figure(figsize=(10,6))
sns.barplot(x=missing_df.head(20).index, y=missing_df.head(20)['% Missing'])
plt.xticks(rotation=90)
plt.title("Top 20 Columns with Missing Data (%)")
plt.tight_layout()
plt.show()

# 4. Key Telemetry Feature Checks
key_fields = [
    "GPS:Lat", "GPS:Long", "IMU_ATTI(0):alti:D",
    "IMU_ATTI(0):accelComposite:C", "IMU_ATTI(0):gyroComposite:C",
    "BatteryInfo:vol_t:D", "Motor:Speed:RFront", "Motor:Speed:LFront",
    "Motor:Speed:RBack", "Motor:Speed:LBack"
]

available_fields = [f for f in key_fields if f in df.columns]
print("\n🛰 Available Key Telemetry Fields:")
print(available_fields)

# 5. Plot GPS Path (if available)
if {"GPS:Lat", "GPS:Long"}.issubset(df.columns):
    plt.figure(figsize=(8,6))
    plt.plot(df["GPS:Long"], df["GPS:Lat"], linewidth=1)
    plt.title("Drone Flight Path")
    plt.xlabel("Longitude")
    plt.ylabel("Latitude")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# 6. Altitude over Time
if "IMU_ATTI(0):alti:D" in df.columns:
    plt.figure(figsize=(10,5))
    plt.plot(df["IMU_ATTI(0):alti:D"], linewidth=1.2)
    plt.title("Altitude over Time")
    plt.xlabel("Time Index")
    plt.ylabel("Altitude (m)")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# 7. Battery Voltage
if "BatteryInfo:vol_t:D" in df.columns:
    plt.figure(figsize=(10,5))
    plt.plot(df["BatteryInfo:vol_t:D"], color='orange', linewidth=1.2)
    plt.title("Battery Voltage over Time")
    plt.xlabel("Time Index")
    plt.ylabel("Voltage (mV)")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# 8. Motor Speeds
motor_cols = [c for c in df.columns if "Motor:Speed" in c]
if motor_cols:
    plt.figure(figsize=(10,5))
    for c in motor_cols:
        plt.plot(df[c], label=c, linewidth=1)
    plt.legend()
    plt.title("Motor Speeds Over Time")
    plt.xlabel("Time Index")
    plt.ylabel("Motor Speed (RPM)")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Select only numeric columns
num_df = df.select_dtypes(include=[np.number]).copy()

# Drop columns with too many missing values
num_df = num_df.dropna(axis=1, thresh=len(num_df) * 0.9)

# Drop columns with zero or near-zero variance
low_var_cols = [c for c in num_df.columns if num_df[c].std() < 1e-6]
num_df = num_df.drop(columns=low_var_cols, errors='ignore')

# If still empty or single column, skip safely
if num_df.shape[1] <= 1:
    print(" Not enough numeric columns for correlation heatmap.")
else:
    # Fill remaining NaNs (to avoid NaN correlations)
    num_df = num_df.fillna(method='ffill').fillna(method='bfill')

    # Compute correlation
    corr = num_df.corr()

    # Plot
    plt.figure(figsize=(12, 10))
    sns.heatmap(
        corr,
        cmap='coolwarm',
        center=0,
        annot=False,
        square=True,
        linewidths=0.3,
        cbar_kws={'label': 'Correlation Coefficient'}
    )
    plt.title("Filtered Correlation Heatmap (Only Valid, Non-Constant Numeric Features)")
    plt.tight_layout()
    plt.show()